server:
  port: 2222

# 服务提供方名称
spring:
  application:
    name: pro-service
  datasource:
    url: jdbc:mysql://192.168.36.37:3306/test
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

---
# 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
