#server:
#  port: 1113
#
#spring:
#  application: eureka-server
#
#---
### 配置注册中心集群peer1,peer2,peer3
#eureka:
#  instance:
#    hostname: peer3
#  client:
#    #register-with-eureka: false
#    #fetch-registry: false
#    serviceUrl:
#      defaultZone: http://peer1:1111/eureka/